# Name of the workflow
name: Build TIL README

# Define when the workflow will run
on:
  push:
    branches:
      - main

# Define the job(s) to be run
jobs:
  build:
    # Define the virtual environment for the job
    runs-on: ubuntu-latest

    # Define the steps of the job
    steps:
      # 1. Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Run the Python script to rename file and build README
      - name: Run script
        run: python build_readme.py

      # 4. Commit all changes (file rename + README update)
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Docs: Auto-rename file and update README"